# Generated by Django 6.0.2 on 2026-02-20 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('orders', '0002_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['order'], name='feedback_order_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['customer'], name='feedback_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['driver'], name='feedback_driver_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['rating'], name='feedback_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-created_at'], name='feedback_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['rating', '-created_at'], name='feedback_rating_date_idx'),
        ),
    ]
