# Generated by Django 6.0.2 on 2026-02-19 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('services', '0002_aiprediction_chatbotlog_delete_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprediction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_ai_predictions', to='orders.order'),
        ),
    ]
