# Generated by Django 6.0.2 on 2026-02-20 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_feedback_customer_alter_feedback_order'),
        ('orders', '0002_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['order'], name='complaint_order_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['customer'], name='complaint_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status'], name='complaint_status_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['-created_at'], name='complaint_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', '-created_at'], name='complaint_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['order'], name='cmp_fb_order_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['customer'], name='cmp_fb_cust_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['rating'], name='cmp_fb_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-created_at'], name='cmp_fb_recent_idx'),
        ),
    ]
