# Generated by Django 6.0.2 on 2026-02-20 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_performance_indexes'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['date'], name='analytics_snapshot_date_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['-created_at'], name='analytics_snapshot_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='geofenceevent',
            index=models.Index(fields=['driver'], name='geofence_driver_idx'),
        ),
        migrations.AddIndex(
            model_name='geofenceevent',
            index=models.Index(fields=['order'], name='geofence_order_idx'),
        ),
        migrations.AddIndex(
            model_name='geofenceevent',
            index=models.Index(fields=['event_type'], name='geofence_event_idx'),
        ),
        migrations.AddIndex(
            model_name='geofenceevent',
            index=models.Index(fields=['zone_type'], name='geofence_zone_idx'),
        ),
        migrations.AddIndex(
            model_name='geofenceevent',
            index=models.Index(fields=['driver', '-timestamp'], name='geofence_driver_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='trackinganalytics',
            index=models.Index(fields=['order'], name='tracking_analytics_order_idx'),
        ),
        migrations.AddIndex(
            model_name='trackinganalytics',
            index=models.Index(fields=['-created_at'], name='tracking_analytics_recent_idx'),
        ),
    ]
