# Generated by Django 6.0.2 on 2026-02-19 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('PICKED', 'Picked'), ('IN_PROCESS', 'In Process'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pickup_proof', models.TextField(blank=True, null=True)),
                ('delivery_proof', models.TextField(blank=True, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default=1)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('IN_WASH', 'In Wash'), ('IRONING', 'Ironing'), ('DELIVERED', 'Delivered'), ('MISSING', 'Missing')], default='RECEIVED', max_length=20)),
                ('special_instruction', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='orders.order')),
            ],
        ),
    ]
