# Generated by Django 6.0.2 on 2026-02-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_driverlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='distance_remaining_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='eta_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_proof_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_proof_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/delivery/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/pickup/'),
        ),
    ]
